spring.datasource.url=jdbc:postgresql://localhost:5432/goodsoft_auth?currentSchema=authorization
spring.datasource.username=postgres
spring.datasource.password=unicorn

mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.messages.basename=messages
spring.messages.encoding=UTF-8